import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Accordion from '../components/Accordion'


export const dropdownData = [

  {
    "title": "Lorem Ipsum 1",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.Odio dignissimos ratione, porro aliquam fugiat tempore itaque id hic eius doloribus delectus excepturi, possimus quos accusantium velit praesentium voluptas provident nulla!"
  },
  {
    "title": "Lorem Ipsum 2",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.Odio dignissimos ratione, porro aliquam fugiat tempore itaque id hic eius doloribus delectus excepturi, possimus quos accusantium velit praesentium voluptas provident nulla!"
  },
  {
    "title": "Lorem Ipsum 3",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.Odio dignissimos ratione, porro aliquam fugiat tempore itaque id hic eius doloribus delectus excepturi, possimus quos accusantium velit praesentium voluptas provident nulla!"
  },
  {
    "title": "Lorem Ipsum 4",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.Odio dignissimos ratione, porro aliquam fugiat tempore itaque id hic eius doloribus delectus excepturi, possimus quos accusantium velit praesentium voluptas provident nulla!"
  },
  {
    "title": "Lorem Ipsum 5",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.Odio dignissimos ratione, porro aliquam fugiat tempore itaque id hic eius doloribus delectus excepturi, possimus quos accusantium velit praesentium voluptas provident nulla!"
  },

]

const Home: NextPage = () => {


  const [isOpen, setIsOpen] = useState(false)
  return (
    <div className="flex flex-col min-h-screen ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid justify-items-center w-full px-3.5 md:px-36 lg:px-80">
        <h3 className="text-gray-700 font-bold text-xl py-16 md:text-3xl md:font-semibold">Frequently Asked</h3>

        <hr className="bg-gray-500 w-full mb-5 " />
        {
          dropdownData && dropdownData.map((e: any) => {
            return (
              <Accordion title={e.title} description={e.description} key="title"/>
            )
          })
        }

      </main>

      <footer >

      </footer>
    </div>
  )
}

export default Home
